- normal: [normal1]
- normal: [normal2]
- blocked: [blocked1]
- normal: [normal3]
- normal: [normal4]
- spillage: [spillage1]
- normal: [normal5]
- normal: [normal6]
- normal: [normal7]
- overloaded: [overloaded1]
- normal: [normal8]
- normal: [normal9]
- blocked: [blocked2]
- normal: [normal10]
- normal: [normal11]
- spillage: [spillage2]
- normal: [normal12]
- normal: [normal13]
- normal: [normal14]
- overloaded: [overloaded2]
- normal: [normal15]
- normal: [normal16]
- blocked: [blocked3]
- normal: [normal17]
- normal: [normal18]
- spillage: [spillage3]
- normal: [normal19]
- normal: [normal20]
- misalignment: [misalignment1]
- normal: [normal21]
- normal: [normal22]
- spillage: [spillage4]
- normal: [normal23]
- normal: [normal24]
- blocked: [blocked4]
- normal: [normal25]
- normal: [normal26]
- spillage: [spillage5]
- normal: [normal27]
- normal: [normal28]
- misalignment: [misalignment2]
- normal: [normal29]
- normal: [normal30]
- spillage: [spillage6]
- normal: [normal31]
