"/tf":
  history:    keep_last      # required
  depth:      1
  reliability: best_effort
  durability:  volatile

"/tf_static":
  history:    keep_last      # required
  depth:      1
  reliability: reliable
  durability:  transient_local
